<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dokumen extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dokumen_model');
        $this->load->library('form_validation');
    }
     public function direct($id)
    {
        $data = array('id_detail_unit' => $id, );
        $this->session->set_userdata($data);
        redirect(site_url('Dokumen'));
    }
    public function index()
    {
       $id_detail_unit = $this->session->userdata('id_detail_unit');
        $start = intval($this->input->get('start'));       
        $dokumen = $this->Dokumen_model->get_limit_data($id_detail_unit);

       
        $data = array(
            'dokumen_data' => $dokumen,    
             
            'button' => 'Create',
            'start' => $start,
            'title' => 'Detail_unit',
            'action' => site_url('dokumen/create_action'),
	    'id_dokumen' => set_value('id_dokumen'),
	    'nama_dokumen' => set_value('nama_dokumen'),
	    'dokumen' => set_value('dokumen'),
	    'id_detail_unit' => set_value('id_detail_unit',$id_detail_unit),
	);      
       
        $this->template->load('template/body','dokumen/dokumen_list', $data);
    }

    public function create_action() 
    {   $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->index();
        } else {
        $nama_dokumen = $this->input->post('nama_dokumen',TRUE);
        $nm = "$nama_dokumen";
        $config['upload_path'] = './asset/dokumen/';
        $config['allowed_types'] = 'pdf';
        $config['max_size']  = '50480';
        $config['remove_space'] = TRUE;
        $config['file_name'] = $nm;
        $this->load->library('upload', $config); 
        if ($this->upload->do_upload('dokumen')){
        $upload_data = $this->upload->data();
            $data = array(
        'nama_dokumen' => $this->input->post('nama_dokumen',TRUE),
        'dokumen' => $upload_data['file_name'],
        'id_detail_unit' => $this->input->post('id_detail_unit',TRUE),
        );

             $this->Dokumen_model->insert($data);
            $this->session->set_flashdata('create', 'ready');
            redirect(site_url('dokumen'));
        }else{
            $this->session->set_flashdata('message7', 'ready');
             $this->session->set_flashdata('isi', $this->upload->display_errors());
             redirect(site_url('dokumen'));
        }
      
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Dokumen_model->get_by_id($id);

        if ($row) {
            $this->Dokumen_model->delfile($id);
            $this->Dokumen_model->delete($id);
            $this->session->set_flashdata('delete', 'ready');
            redirect(site_url('dokumen'));
        } else {
            $this->session->set_flashdata('notfound', 'ready');
            redirect(site_url('dokumen'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_dokumen', 'nama dokumen', 'trim|required');
	$this->form_validation->set_rules('id_detail_unit', 'id detail unit', 'trim|required');

	$this->form_validation->set_rules('id_dokumen', 'id_dokumen', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Dokumen.php */
/* Location: ./application/controllers/Dokumen.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-01-24 08:02:30 */
/* http://harviacode.com */