<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dokumen_model extends CI_Model
{

    public $table = 'dokumen';
    public $id = 'id_dokumen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
 
    // get data with limit and search
    function get_limit_data($id) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_detail_unit',$id);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
     function delfile($id){

     $this->db->where($this->id,$id);
     $query = $this->db->get($this->table);
     $row = $query->row();

     unlink("./asset/dokumen/$row->dokumen");
    }

}

/* End of file Dokumen_model.php */
/* Location: ./application/models/Dokumen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-01-24 06:52:04 */
/* http://harviacode.com */